### ISSUE TITLE
.editorconfig change

### ISSUE THREAD

**Issue by TheMysteriousVincent** [Saborknight/9liners-and-notepad#22]
Could we change the `.editorconfig`'s SQF indents to spaces because they're better to read in code on GitHub?

**Comment by Saborknight** [comment]
Damn, those are big. I've never noticed, I'm normally not looking at the source code on github.

There have been numerous suggestions to fix this 8 tab size deal. The easiest seems to be [this comment](https://github.com/isaacs/github/issues/170#issuecomment-60220018) or the comment below that one. I'm going to go the css route.

I don't want to change the source code just because github is silly with tab sizes...

**Comment by TheMysteriousVincent** [comment]
But how come that you use tabs?

**Comment by Saborknight** [comment]
To avoid user error and added spaces between indent and code. I've seen in the past a lot of code ill formatted because of this. The mistakes are so small that the developer (me included a few times when working on a space indented project) just misses them.

It also makes more sense to me... a single entity for a single purpose: a single indent.

I am aware that it's a lot of personal preference as well, but personal preference is a silly argument to make in the realms of developing in a team.

If I am wrong, I'm open to discussion, but those are what I've rationalised about the matter.
