### ISSUE TITLE
Packages for each item

### ISSUE THREAD

**Issue by TheMysteriousVincent** [Saborknight/9liners-and-notepad#7]
Feature request:
If we would add a seperation of the items, the enduser could choose between specific items easily.
More detail:
We could split those items into single `.pbo` packages.

Is there anything against this idea?

**Comment by Saborknight** [comment]
The only reason I could think of, where that would be a bad thing, would be when units want to add all their favourite PBOs into their one mod. At that point there would be an uncomfortable amount of PBOs from 9Liners & Notepad itself.

Then again, I see your reasoning, since a person doesn't want to mess around with certain sheets... Although this is only really a disruptive fact when #2 and/or #1 come into effect. Before then, they're just extra keybindings which are taken up.

Perhaps instead we should setup some Addon Options where the user can choose which format of pages to see. So it's a form of hiding each format from the future planned navigation menu and ACE interactions, as mentioned above.

**Comment by TheMysteriousVincent** [comment]
Well then I would recommend some kind of mission configor parameter or a mission module to disable items aswell as using the CBA settings framework to set variables from a server.
Although, it might be interesting if there were any ArmA 3 items belonging to the sheets.

**Comment by Saborknight** [comment]
Using the CBA Settings framework is what I had in mind when I was writing the comment above. However, wouldn't offering a mission module bring this client-side mod back into a server-side mod?

**Comment by TheMysteriousVincent** [comment]
I agree on the point of a client side model. But first we do have to reorganize the single package!

**Comment by TheMysteriousVincent** [comment]
Steam does know it too. Its just like git, but less complex than git. Steam does not care about the amount or type of file. It just replaces wrong and right byte segments.
